# Focuses on major updates, dependabot creates separate PRs for each dependency update
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'daily'
