codecov:
  require_ci_to_pass: yes

fixes:
  - '::ci/'

coverage:
  status:
    project:
      default:
        target: auto
        threshold: null
        if_not_found: success
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: null
        if_not_found: success
        only_pulls: false

ignore:
  - 'node_modules/'
