version: '3.9'
services:
  server:
    build: .
    container_name: poku-website
    restart: always
    ports:
      - '127.0.0.1:${APP_PORT}:${APP_PORT}'
    environment:
      APP_PORT: ${APP_PORT}
