# Groups minor and patch dependency updates into a single PR.
name: '⏫ Bot (Website) — Dependencies'

on:
  workflow_dispatch:

env:
  TITLE: 'chore(website): update dependencies'
  BRANCH: 'deps-website'
  PACKAGE_PATH: 'website'
  BODY: '- 🤖 Update website dependencies'
  LABELS: |
    dependencies
    website

jobs:
  update-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.repository.fork == false
    name: Update
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v6

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: lts/*

      - name: ➕ Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: 🔒 Checking if branch is main
        run: |
          MAIN_BRANCH=$(git remote show origin | grep 'HEAD branch' | awk '{print $NF}')
          if [ "${{ env.BRANCH }}" = "$MAIN_BRANCH" ]; then
            exit 1
          fi

      - name: 📦 Installing Dependencies
        run: cd ${{ env.PACKAGE_PATH }} && npm ci

      - name: ⏫ Updating Dependencies
        run: cd ${{ env.PACKAGE_PATH }} && npm run update

      - name: ⚙️ Configuring Git
        run: |
          git config --global user.name 'wellwelwel'
          git config --global user.email '46850407+wellwelwel@users.noreply.github.com'
          git update-index --refresh > /dev/null 2>&1 || true

      - name: 🔎 Checking for Changes
        id: check_changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: 🗑️ Deleting Branch
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ env.BRANCH }} || true

      - name: 🚀 Commiting and Pushing Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add .
          git commit -m "${{ env.TITLE }}"
          git push origin HEAD:refs/heads/${{ env.BRANCH }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧙🏻 Creating Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH }}
          title: '${{ env.TITLE }}'
          body: ${{ env.BODY }}
          labels: ${{ env.LABELS }}
          delete-branch: true
