name: '🎖️ CI — Benchmark'

on:
  pull_request:
    paths:
      - '.github/workflows/ci_benchmark.yml'
      - 'benchmark/**'
      - 'src/**'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    name: Compare
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: lts/*

      - name: ➕ Actions — Setup Hyperfine
        run: cargo install --locked hyperfine

      - name: ➕ Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: ➕ Cache dependencies (Benchmark)
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-benchmark-${{ hashFiles('benchmark/package-lock.json') }}
          restore-keys: npm-benchmark-

      - name: 📦 Installing Dependencies
        run: npm ci

      - name: 🚀 Building Poku
        run: |
          npm run build
          npm --prefix benchmark ci

      - name: 🎖️ Rock it
        run: npm run benchmark

      - name: 💬 Comment
        uses: wellwelwel/bot@v1.0.0
        with:
          update-if-includes: 'Benchmarks'
          comment-from-file: './benchmark/output.md'
