name: '🔬 CI — Bun'

on:
  pull_request:
    paths:
      - '.github/workflows/ci_compatibility-bun.yml'
      - '.nycrc/**'
      - 'src/**'
      - 'test/**'
      - 'tools/**'
      - 'codecov.yml'
      - 'package-lock.json'
      - 'package.json'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  bun:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        bun-version: ['latest']
    name: ${{ matrix.bun-version }}
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v6

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: lts/*

      - name: ➕ Actions - Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: ➕ Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: 📦 Installing Dependencies
        run: npm ci

      - name: 🤹🏻‍♀️ Building the Project
        run: npm run build

      - name: 🔬 Bun ${{ matrix.bun-version }}
        run: bun run test:bun

      - name: ☔️ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: bun
          name: codecov-umbrella-bun
