name: '🍎 CI — Coverage'

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/ci_coverage-osx.yml'
      - '.nycrc/**'
      - 'src/**'
      - 'test/**'
      - 'tools/**'
      - 'codecov.yml'
      - 'package-lock.json'
      - 'package.json'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  osx:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    name: macOS
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v6

      - name: ➕ Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-osx-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-osx-

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: lts/*

      - name: 📦 Installing Dependencies
        run: npm ci

      - name: 🧪 Checking for Coverage
        run: npm run test:coverage

      - name: ☔️ Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: osx
          name: codecov-umbrella-osx
